spring:
  liquibase:
    url: jdbc:postgresql://localhost:15432/sample
    user: postgres
    password: password
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/sample
    username: postgres
    password: password
