services:
  postgresql:
    image: postgres:14.9
    ports:
      - "15432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample

networks:
  backend: